name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./ecommerce-backend
        run: npm install

      - name: Run migrations
        working-directory: ./ecommerce-backend
        run: npx prisma migrate deploy

      - name: Run tests
        working-directory: ./ecommerce-backend
        env:
          DATABASE_URL: postgresql://postgres:kalemeuy123@localhost:5433/ecommerce_db
        run: npm test
